version: '3'

volumes:
  dockovpn:
    driver: local

services:

  dockovpn:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: my-local-dockovpn
    cap_add:
      - NET_ADMIN
    ports:
      - 0.0.0.0:${HOST_TUN_PORT}:1194/tcp
    volumes:
      - dockovpn:/opt/Dockovpn_data
    environment:
      - HOST_ADDR
      - NET_ADAPTER
      - HOST_TUN_PORT
