version: '3'

volumes:
  dockovpn:
    driver: local

services:
  dockovpn:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: my-local-dockovpn
    cap_add:
      - NET_ADMIN
    ports:
      - 0.0.0.0:1194:1194/tcp
    env_file: .env
    volumes:
      - dockovpn:/opt/Dockovpn_data
